services:
  server:
    build: ./server
    ports:
      - 5050:5000
    command: npm run dev
    volumes:
      - ./server/src/:/app/src/
      - /app/node_modules

  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db

  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client/src/:/app/src/
      - ./client/public/:/app/public/
    environment:
      - CHOKIDAR_USEPOLLING=true
